# Generated by Django 3.2 on 2021-05-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(null=True, upload_to='images/')),
                ('title', models.CharField(blank=True, max_length=250)),
                ('text', models.TextField(blank=True)),
            ],
        ),
    ]
