# Generated by Django 3.2 on 2021-05-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_searchresults_searched_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresults',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='searchresults',
            name='searched_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
